server:
  port: 80
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/workday?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
